Traceback (most recent call last):
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\nbclient\client.py", line 1093, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "c:\users\user\appdata\local\programs\python\python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\nbclient\client.py", line 559, in async_execute
    await self.async_execute_cell(
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\nbclient\client.py", line 854, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\nbclient\client.py", line 756, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
def noise(array):
    """
    AÃ±ade ruido a la imagen 
    """
    noise_factor = 0.4
    noisy_array = array + noise_factor * np.random.normal(
        loc=0.0, scale=1.0, size=array.shape
    )

    return np.clip(noisy_array, 0.0, 1.0) # clip para dejar los valores en [0.0, 1.0]

# Crea una copia de los datos con ruido agregado
noisy_x_train = noise(x_train)
noisy_x_test = noise(x_test)
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mMemoryError[0m                               Traceback (most recent call last)
[1;32m~\AppData\Local\Temp/ipykernel_11996/2381910292.py[0m in [0;36m<cell line: 13>[1;34m()[0m
[0;32m     11[0m [1;33m[0m[0m
[0;32m     12[0m [1;31m# Crea una copia de los datos con ruido agregado[0m[1;33m[0m[1;33m[0m[0m
[1;32m---> 13[1;33m [0mnoisy_x_train[0m [1;33m=[0m [0mnoise[0m[1;33m([0m[0mx_train[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m     14[0m [0mnoisy_x_test[0m [1;33m=[0m [0mnoise[0m[1;33m([0m[0mx_test[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\AppData\Local\Temp/ipykernel_11996/2381910292.py[0m in [0;36mnoise[1;34m(array)[0m
[0;32m      4[0m     """
[0;32m      5[0m     [0mnoise_factor[0m [1;33m=[0m [1;36m0.4[0m[1;33m[0m[1;33m[0m[0m
[1;32m----> 6[1;33m     noisy_array = array + noise_factor * np.random.normal(
[0m[0;32m      7[0m         [0mloc[0m[1;33m=[0m[1;36m0.0[0m[1;33m,[0m [0mscale[0m[1;33m=[0m[1;36m1.0[0m[1;33m,[0m [0msize[0m[1;33m=[0m[0marray[0m[1;33m.[0m[0mshape[0m[1;33m[0m[1;33m[0m[0m
[0;32m      8[0m     )

[1;32mmtrand.pyx[0m in [0;36mnumpy.random.mtrand.RandomState.normal[1;34m()[0m

[1;32m_common.pyx[0m in [0;36mnumpy.random._common.cont[1;34m()[0m

[1;31mMemoryError[0m: Unable to allocate 359. MiB for an array with shape (60000, 28, 28, 1) and data type float64
MemoryError: Unable to allocate 359. MiB for an array with shape (60000, 28, 28, 1) and data type float64

