Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# usando el m√©todo de clase
path = 'https://raw.githubusercontent.com/AprendizajeProfundo/Libro_Fundamentos_Programacion/main/Python/Datos/cuenta.csv'
mi_cuenta = CuentaBancaria.from_csv(path)
print(mi_cuenta.cliente, mi_cuenta.numero_cuenta, mi_cuenta.saldo, mi_cuenta.creada_en)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
Input [0;32mIn [6][0m, in [0;36m<cell line: 3>[0;34m()[0m
[1;32m      1[0m [38;5;66;03m# usando el m√©todo de clase[39;00m
[1;32m      2[0m path [38;5;241m=[39m [38;5;124m'[39m[38;5;124mhttps://raw.githubusercontent.com/AprendizajeProfundo/Libro_Fundamentos_Programacion/main/Python/Datos/cuenta.csv[39m[38;5;124m'[39m
[0;32m----> 3[0m mi_cuenta [38;5;241m=[39m [43mCuentaBancaria[49m[38;5;241;43m.[39;49m[43mfrom_csv[49m[43m([49m[43mpath[49m[43m)[49m
[1;32m      4[0m [38;5;28mprint[39m(mi_cuenta[38;5;241m.[39mcliente, mi_cuenta[38;5;241m.[39mnumero_cuenta, mi_cuenta[38;5;241m.[39msaldo, mi_cuenta[38;5;241m.[39mcreada_en)

Input [0;32mIn [5][0m, in [0;36mCuentaBancaria.from_csv[0;34m(cls, filepath)[0m
[1;32m     17[0m [38;5;129m@classmethod[39m
[1;32m     18[0m [38;5;28;01mdef[39;00m [38;5;21mfrom_csv[39m([38;5;28mcls[39m, filepath):
[0;32m---> 19[0m     [38;5;28;01mwith[39;00m [38;5;28;43mopen[39;49m[43m([49m[43mfilepath[49m[43m,[49m[43m [49m[38;5;124;43m"[39;49m[38;5;124;43mr[39;49m[38;5;124;43m"[39;49m[43m)[49m [38;5;28;01mas[39;00m f:
[1;32m     20[0m         fila [38;5;241m=[39m csv[38;5;241m.[39mreader(f)[38;5;241m.[39m[38;5;21m__next__[39m()
[1;32m     21[0m         cliente, numero_cuenta [38;5;241m=[39m fila

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: 'https://raw.githubusercontent.com/AprendizajeProfundo/Libro_Fundamentos_Programacion/main/Python/Datos/cuenta.csv'
FileNotFoundError: [Errno 2] No such file or directory: 'https://raw.githubusercontent.com/AprendizajeProfundo/Libro_Fundamentos_Programacion/main/Python/Datos/cuenta.csv'

