Traceback (most recent call last):
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\nbclient\client.py", line 1093, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "c:\users\user\appdata\local\programs\python\python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\nbclient\client.py", line 559, in async_execute
    await self.async_execute_cell(
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\nbclient\client.py", line 854, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\nbclient\client.py", line 756, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
print("La correlaci√≥n de RM y MEDV es:", relation_rm_medv(rm, Y))
print("La media de las viviendas con un n√∫mero de viviendas entre 5 y 6 es:", price_mean(rm, Y))
medv_hist(Y)
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mNameError[0m                                 Traceback (most recent call last)
[1;32m~\AppData\Local\Temp/ipykernel_1368/409557999.py[0m in [0;36m<module>[1;34m[0m
[1;32m----> 1[1;33m [0mprint[0m[1;33m([0m[1;34m"La correlaci√≥n de RM y MEDV es:"[0m[1;33m,[0m [0mrelation_rm_medv[0m[1;33m([0m[0mrm[0m[1;33m,[0m [0mY[0m[1;33m)[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      2[0m [0mprint[0m[1;33m([0m[1;34m"La media de las viviendas con un n√∫mero de viviendas entre 5 y 6 es:"[0m[1;33m,[0m [0mprice_mean[0m[1;33m([0m[0mrm[0m[1;33m,[0m [0mY[0m[1;33m)[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m      3[0m [0mmedv_hist[0m[1;33m([0m[0mY[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;31mNameError[0m: name 'rm' is not defined
NameError: name 'rm' is not defined

